Repository codescalersinternships/CSHR, pull requests merged in 2022-09, with the labels that each got.

#104 Added cors.
  server/settings.py
Labels: enhancement

#117 Update config.temp file.
  config/.env.template
Labels: enhancement

#120 Add custom datetime parser based on the fronend consept.
  server/cshr/serializers/event.py
  server/cshr/serializers/meetings.py
  server/cshr/serializers/users.py
  server/cshr/serializers/vacations.py
  server/cshr/tests/test_event.py
  server/cshr/tests/test_meetings.py
  server/cshr/utils/parse_date.py
  server/cshr/views/event.py
  server/cshr/views/meetings.py
  server/settings.py
Labels: enhancement

#119 add request endpoint with testing
  server/cshr/routs/requests.py
  server/cshr/serializers/compensation.py
  server/cshr/serializers/hr_letters.py
  server/cshr/serializers/vacations.py
  server/cshr/services/requests.py
  server/cshr/services/vacations.py
  server/cshr/tests/test_request.py
  server/cshr/views/requests.py
  server/cshr/views/vacations.py
  server/urls.py
Labels: enhancement

#123 Development send email on request
  dump.rdb
  server/cshr/celery/send_email.py
  server/cshr/serializers/compensation.py
  server/cshr/utils/send_email.py
  server/cshr/views/compensation.py
  server/cshr/views/hr_letters.py
  server/cshr/views/vacations.py
Labels: enhancement

#139 merging migrations
  server/cshr/migrations/0032_merge_20220913_0759.py
Labels: bug

#151 Fix landing page issues, update docker-compose, MakeFile files
  Makefile
  docker-compose.yml
  server/cshr/api/response.py
  server/cshr/migrations/0038_merge_20220918_0933.py
  server/cshr/migrations/0041_merge_20220918_0946.py
  server/cshr/migrations/0042_alter_hrletters_date.py
  server/cshr/migrations/0043_alter_hrletters_date.py
  server/cshr/migrations/0044_user_background_color_alter_user_image.py
  server/cshr/models/hr_letters.py
  server/cshr/models/users.py
  server/cshr/routs/company_properties.py
  server/cshr/routs/compensation.py
  server/cshr/routs/evaluation.py
  server/cshr/routs/event.py
  server/cshr/routs/hr_letters.py
  server/cshr/routs/meetings.py
  server/cshr/routs/myinfo.py
  server/cshr/routs/office.py
  server/cshr/routs/training_courses.py
  server/cshr/routs/users.py
  server/cshr/routs/vacations.py
  server/cshr/serializers/auth.py
  server/cshr/serializers/users.py
  server/cshr/services/event.py
  server/cshr/services/landing_page.py
  server/cshr/services/meetings.py
  server/cshr/tests/test_auth.py
  server/cshr/tests/test_company_properties.py
  server/cshr/tests/test_compensation.py
  server/cshr/tests/test_event.py
  server/cshr/tests/test_hr_letters.py
  server/cshr/tests/test_meetings.py
  server/cshr/tests/test_office.py
  server/cshr/tests/test_request.py
  server/cshr/tests/test_training_courses.py
  server/cshr/tests/test_userEvaluation.py
  server/cshr/tests/test_users.py
  server/cshr/tests/test_vacation.py
  server/cshr/utils/generate.py
  server/cshr/views/company_properties.py
  server/cshr/views/compensation.py
  server/cshr/views/evaluation.py
  server/cshr/views/event.py
  server/cshr/views/hr_letters.py
  server/cshr/views/meetings.py
  server/cshr/views/office.py
  server/cshr/views/training_courses.py
  server/cshr/views/users.py
  server/cshr/views/vacations.py
  server/settings.py
Labels: enhancement

#156 Implement team endpoint
  Makefile
  server/cshr/migrations/0045_alter_publicholidays_date.py
  server/cshr/models/users.py
  server/cshr/models/vacations.py
  server/cshr/routs/users.py
  server/cshr/serializers/users.py
  server/cshr/services/users.py
  server/cshr/views/event.py
  server/cshr/views/users.py
Labels: enhancement

#152 Development team
  client/src/Routes.svelte
  client/src/components/footer/Footer.svelte
  client/src/components/pagination/Pagination.svelte
  client/src/components/requests/Request.svelte
  client/src/components/requests/Requests.svelte
  client/src/components/sidebar/Sidebar.svelte
  client/src/components/table/Table.svelte
  client/src/components/team/Members.svelte
  client/src/components/team/Supervisors.svelte
  client/src/components/team/Team.svelte
  client/src/pages/Team.svelte
  server/cshr/migrations/0041_alter_hrletters_date.py
  server/cshr/migrations/0045_merge_20220919_0851.py
  server/cshr/migrations/0046_alter_hrletters_date.py
Labels: enhancement, Front End Feature

#154 add endpoint to get (vacations - HrLetters - compensations) for user …
  server/cshr/routs/compensation.py
  server/cshr/routs/hr_letters.py
  server/cshr/routs/vacations.py
  server/cshr/services/compensation.py
  server/cshr/services/hr_letters.py
  server/cshr/services/vacations.py
  server/cshr/tests/test_compensation.py
  server/cshr/tests/test_hr_letters.py
  server/cshr/tests/test_vacation.py
  server/cshr/views/compensation.py
  server/cshr/views/hr_letters.py
  server/cshr/views/vacations.py
Labels: enhancement

#158 Development queryset pagination for get all
  server/cshr/tests/test_office.py
  server/cshr/tests/test_userEvaluation.py
  server/cshr/views/company_properties.py
  server/cshr/views/compensation.py
  server/cshr/views/evaluation.py
  server/cshr/views/hr_letters.py
  server/cshr/views/meetings.py
  server/cshr/views/office.py
  server/cshr/views/training_courses.py
  server/cshr/views/users.py
  server/cshr/views/vacations.py
Labels: bug

#162 Development cookies
  client/src/services/cookie/Cookie.ts
  client/src/types.ts
Labels: enhancement

#171 Development notification with redis
  .github/workflows/test.yml
  dump.rdb
  poetry.lock
  pyproject.toml
  server/cshr/celery/send_email.py
  server/cshr/routs/compensation.py
  server/cshr/routs/hr_letters.py
  server/cshr/routs/notifications.py
  server/cshr/routs/vacations.py
  server/cshr/tests/test_compensation.py
  server/cshr/tests/test_hr_letters.py
  server/cshr/tests/test_notifications.py
  server/cshr/tests/test_vacation.py
  server/cshr/utils/email_messages_templates.py
  server/cshr/utils/redis_functions.py
  server/cshr/views/compensation.py
  server/cshr/views/hr_letters.py
  server/cshr/views/notifications.py
  server/cshr/views/vacations.py
  server/urls.py
Labels: enhancement

#170 Development profile
  .github/workflows/build.yml
  .github/workflows/lint.yml
  README.md
  Screenshot_from_2022-09-08_21-23-42.png
  client/package-lock.json
  client/package.json
  client/public/global.css
  client/public/index.html
  client/public/vendor/bootstrap/css/bootstrap.min.css
  client/public/vendor/bootstrap/js/bootstrap.bundle.min.js
  client/rollup.config.js
  client/src/Routes.svelte
  client/src/components/evaluation/Evaluation.svelte
  client/src/components/image/CircularImage.svelte
  client/src/components/profile/Certificates.svelte
  client/src/components/profile/Company.svelte
  client/src/components/profile/Evaluation.svelte
  client/src/components/profile/Profile.svelte
  client/src/components/profile/Salary.svelte
  client/src/components/profile/Skills.svelte
  client/src/components/profile/UserData.svelte
  client/src/components/sidebar/Sidebar.svelte
  client/src/components/users/User.svelte
  client/src/pages/Login.svelte
  client/src/pages/NotAnAdmin.svelte
  client/src/pages/NotLoggedIn.svelte
  client/src/routes/AdminRoute.svelte
  client/src/routes/LoggedRoute.svelte
  client/src/routes/Supervisor.svelte
  client/src/services/authentication/IsAuthenticated.ts
  client/src/services/axios/evaluation/EvaluationDataService.ts
  client/src/services/axios/home/CalendarDataService.ts
  client/src/services/axios/http-common.ts
  client/src/services/axios/login/UserRefreshService.ts
  client/src/services/axios/login/loginDataService.ts
  client/src/services/axios/login/types.ts
  client/src/services/axios/user/UserDataService.ts
  client/src/services/axios/users/UsersDataService.ts
  client/src/services/cookie/Cookie.ts
  client/src/stores.ts
  client/src/types.ts
  package-lock.json
  package.json
Labels: enhancement, Front End Feature
